### ISSUE TITLE
auth 404

### ISSUE THREAD

**Issue by Yangsh0412** [liuliancao/go-admin-angular#1]
大佬，登录一直报错呀

**Comment by liuliancao** [comment]
报啥错 后端也运行了吧 另外 https://github.com/liuliancao/go-admin/blob/main/op-init.sql 这个执行了不  也可以邮箱沟通下 liuliancao@gmail.com

**Comment by liuliancao** [comment]
写了个部署文档 https://blog.liuliancao.com/posts/go-admin-demo/ 可以参考下

**Comment by Yangsh0412** [comment]
> 写了一个部署文档https://blog.liuliancao.com/posts/go-admin-demo/可以参考下

好的，谢谢
